### ISSUE TITLE
Needs a note added,  Pins for hookup are SDA and SCL for SDIO and SCLK

### ISSUE THREAD

**Issue by eadthem** [sparkfun/SparkFun_Si4703_Arduino_Library#3]
There needs to be a note added.

When using anything but the arduino mini.   Not only do you need a level shifter for 5 to 3.3v  BUT
you also must use SDA instead of A4  and SCL instead of A5 for pins.

This code gets it to work on the mega 2560 with a 4 pin I2C level shifter.
int resetPin = 2;
int SDIO = SDA;
int SCLK = SCL;

I also hooked up SEN via the level shifter and connected that to 5V.
I suspect SDA and SCL will work to spec the correct pins on any Arduino including the mini.

This was not clear, until i looked up the pin outs for the Arduino mini,  the whole day i thought the library was doing some weird bit banging for I2C instead of using the purpose made pins.

**Comment by bboyho** [comment]
Yeah, it depends on the architecture that you are using and the logic level. The Arduino Mega 2560 uses  5V logic as opposed to 3.3V and the [I2C pins are in different locations](https://www.arduino.cc/en/reference/wire). I added some notes on the product page, hardware hookup, and related tutorial.
