### ISSUE TITLE
Setting Max to 107.1

### ISSUE THREAD

**Issue by tarbear123** [sparkfun/SparkFun_Si4703_Arduino_Library#4]
how do i set a max Freq of 107.1?
```
void Si4703_Breakout::setChannel(int channel)
{
  //Freq(MHz) = 0.200(in USA) * Channel + 87.5MHz
  //97.3 = 0.2 * Chan + 87.5
  //9.8 / 0.2 = 49
  int newChannel = channel * 10; //973 * 10 = 9730
  newChannel -= 8750; //9730 - 8750 = 980
 #ifdef IN_EUROPE
    newChannel /= 10; //980 / 10 = 98
 #else
  newChannel /= 20; //980 / 20 = 49
 #endif
  ```

**Comment by tarbear123** [comment]
> how do i set a max Freq of 107.1?
> 
> ```
> void Si4703_Breakout::setChannel(int channel)
> {
>   //Freq(MHz) = 0.200(in USA) * Channel + 87.5MHz
>   //97.3 = 0.2 * Chan + 87.5
>   //9.8 / 0.2 = 49
>   int newChannel = channel * 10; //973 * 10 = 9730
>   newChannel -= 8750; //9730 - 8750 = 980
>  #ifdef IN_EUROPE
>     newChannel /= 10; //980 / 10 = 98
>  #else
>   newChannel /= 20; //980 / 20 = 49
>  #endif
> ```

hello? i need help plz

**Comment by edspark** [comment]
Hello, you'll find better technical assistance at our forums under the Radio section: 
https://forum.sparkfun.com/viewforum.php?f=120
